
package de.dpunkt.myaktion.monitor.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "DonationDelegatorService", targetNamespace = "http://ws.monitor.myaktion.dpunkt.de/", wsdlLocation = "http://localhost:9080/my-aktion-monitor/DonationDelegatorService?wsdl")
public class DonationDelegatorService
        extends Service {

    private final static URL DONATIONDELEGATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException DONATIONDELEGATORSERVICE_EXCEPTION;
    private final static QName DONATIONDELEGATORSERVICE_QNAME = new QName("http://ws.monitor.myaktion.dpunkt.de/", "DonationDelegatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/my-aktion-monitor/DonationDelegatorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DONATIONDELEGATORSERVICE_WSDL_LOCATION = url;
        DONATIONDELEGATORSERVICE_EXCEPTION = e;
    }

    public DonationDelegatorService() {
        super(__getWsdlLocation(), DONATIONDELEGATORSERVICE_QNAME);
    }

    public DonationDelegatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DONATIONDELEGATORSERVICE_QNAME, features);
    }

    public DonationDelegatorService(URL wsdlLocation) {
        super(wsdlLocation, DONATIONDELEGATORSERVICE_QNAME);
    }

    public DonationDelegatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DONATIONDELEGATORSERVICE_QNAME, features);
    }

    public DonationDelegatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DonationDelegatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns DonationDelegator
     */
    @WebEndpoint(name = "DonationDelegatorPort")
    public DonationDelegator getDonationDelegatorPort() {
        return super.getPort(new QName("http://ws.monitor.myaktion.dpunkt.de/", "DonationDelegatorPort"), DonationDelegator.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns DonationDelegator
     */
    @WebEndpoint(name = "DonationDelegatorPort")
    public DonationDelegator getDonationDelegatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.monitor.myaktion.dpunkt.de/", "DonationDelegatorPort"), DonationDelegator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DONATIONDELEGATORSERVICE_EXCEPTION != null) {
            throw DONATIONDELEGATORSERVICE_EXCEPTION;
        }
        return DONATIONDELEGATORSERVICE_WSDL_LOCATION;
    }

}
